// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYG6pV_86t4xS3mGkStqkQZ2Sn-kj34tA',
    appId: '1:374063956208:web:0e9693e8b909f34aa10235',
    messagingSenderId: '374063956208',
    projectId: 'bacanusantara-app',
    authDomain: 'bacanusantara-app.firebaseapp.com',
    storageBucket: 'bacanusantara-app.firebasestorage.app',
    measurementId: 'G-RWRXN0M7WX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXiE38izEMtLWRT1yXkz3TlDxSahqH-Bk',
    appId: '1:374063956208:android:a976ef5f2c32c604a10235',
    messagingSenderId: '374063956208',
    projectId: 'bacanusantara-app',
    storageBucket: 'bacanusantara-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh9pPNoJGP0Zy17H51DNfGwfP8rRmvmGo',
    appId: '1:374063956208:ios:5bda9482a6a0af81a10235',
    messagingSenderId: '374063956208',
    projectId: 'bacanusantara-app',
    storageBucket: 'bacanusantara-app.firebasestorage.app',
    iosClientId: '374063956208-idt7de9k1kcmvmr33cbtneqkkkltmjpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacaNusantara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh9pPNoJGP0Zy17H51DNfGwfP8rRmvmGo',
    appId: '1:374063956208:ios:5bda9482a6a0af81a10235',
    messagingSenderId: '374063956208',
    projectId: 'bacanusantara-app',
    storageBucket: 'bacanusantara-app.firebasestorage.app',
    iosClientId: '374063956208-idt7de9k1kcmvmr33cbtneqkkkltmjpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.bacaNusantara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYG6pV_86t4xS3mGkStqkQZ2Sn-kj34tA',
    appId: '1:374063956208:web:4ca90e3d8690006da10235',
    messagingSenderId: '374063956208',
    projectId: 'bacanusantara-app',
    authDomain: 'bacanusantara-app.firebaseapp.com',
    storageBucket: 'bacanusantara-app.firebasestorage.app',
    measurementId: 'G-HXFE12ZM34',
  );
}
